# Generated by Django 2.2.13 on 2021-02-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('carmodel', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('mdate', models.DateField()),
                ('car_serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('chasis_no', models.IntegerField(unique=True)),
                ('engine_no', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('status', models.CharField(max_length=100)),
                ('shipping_date', models.DateField()),
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryManagementSystem.ProductModel')),
            ],
        ),
    ]
